### ISSUE TITLE
Personagem vibrando ao forçar o contato com as paredes

### ISSUE THREAD

**Issue by Crekpozer** [Hollow-Ice-Studio/1nnocent#3]
Quando o personagem entra em contato com a parede e o jogador continua se empurrando contra ela, o personagem cria uma especie de vibração.

Isso se da pois o codigo faz com que o personagem OBRIGATORIAMENTE se jogue dentro da parede e o box collider faz com que ele saia, isso permite que o jogador abuse disso e consigo subir ou até atravessar as paredes.

Encontrei uma solução para isso, está no link a seguir:

https://answers.unity.com/questions/1563211/vibrating-character-on-collision-with-wall.html

**Comment by manoger** [comment]
Aplicado alteração.
Agora o personagem se move via rigidbody ao invés de translate e também foi adicionado um collider extra no Adam com fricção zero ao entorno dele para não grudar na parede.
